### ISSUE TITLE
Manual-Installation wiki link doesn't exist

### ISSUE THREAD

**Issue by jcelliott** [oh-my-fish/framework#1]
Looks like everything was recently moved from a different repo, so maybe the wiki hasn't been migrated yet?

**Comment by bucaran** [comment]
@jcelliott The project is going through some chaos at the moment. We will be back online shortly. Hopefully.

**Comment by bpinto** [comment]
@jcelliott this is the new repo location: https://github.com/oh-my-fish/oh-my-fish
It looks brand new, but we are working towards recovering it to it's original shape. The code though is exactly how it used to be.

**Comment by jcelliott** [comment]
Looks like I chose the wrong time to get started. Thanks for clarifying.

**Comment by bpinto** [comment]
@jcelliott Yeah... well, it was something totally unexpected. Anyway, if you run the install script, everything will remain working as it should. Nice to have you on board.
